// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package adm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdmClient is the client API for Adm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdmClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type admClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmClient(cc grpc.ClientConnInterface) AdmClient {
	return &admClient{cc}
}

func (c *admClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/adm.Adm/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmServer is the server API for Adm service.
// All implementations must embed UnimplementedAdmServer
// for forward compatibility
type AdmServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAdmServer()
}

// UnimplementedAdmServer must be embedded to have forward compatible implementations.
type UnimplementedAdmServer struct {
}

func (UnimplementedAdmServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAdmServer) mustEmbedUnimplementedAdmServer() {}

// UnsafeAdmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmServer will
// result in compilation errors.
type UnsafeAdmServer interface {
	mustEmbedUnimplementedAdmServer()
}

func RegisterAdmServer(s grpc.ServiceRegistrar, srv AdmServer) {
	s.RegisterService(&Adm_ServiceDesc, srv)
}

func _Adm_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adm.Adm/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Adm_ServiceDesc is the grpc.ServiceDesc for Adm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Adm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adm.Adm",
	HandlerType: (*AdmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Adm_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adm.proto",
}
