---
--- 令牌桶限流算法
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by itianyu.
--- DateTime: 2026/9/6 09:11
---
local rate = tonumber(ARGV[1])
local capacity = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
local requested = tonumber(ARGV[4])
local fill_time = capacity / rate
local ttl = math.floor(fill_time * 2)
local last_tokens = redis.call("GET", KEYS[1])
if not last_tokens then
    last_tokens = capacity
end
local last_refreshed = redis.call("GET", KEYS[2])
if not last_refreshed then
    last_refreshed = 0
end
local delta = math.max(0, now - last_refreshed)
local filled_tokens = math.min(capacity, last_tokens + (delta * rate))
local allowed = false
if filled_tokens >= requested then
    allowed = true
    filled_tokens = filled_tokens - requested
end
redis.call("SET", KEYS[1], filled_tokens, "EX", ttl)
redis.call("SET", KEYS[2], now, "EX", ttl)
return allowed