---
--- 滑动窗口算法
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by itianyu.
--- DateTime: 2026/9/6 14:23
---
local rate = tonumber(ARGV[1])
local window = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
redis.call("LPUSH", KEYS[1], now)
local len = tonumber(redis.call("LLEN", KEYS[1]))
redis.call("EXPIRE", KEYS[1], window / rate * 2)
local allow = true
if len > rate then
    --redis.log(redis.LOG_WARNING, "alllow...", window)
    if now - tonumber(redis.call("LINDEX", KEYS[1], len - 1)) <= window then
        allow = false
    end
    redis.call("RPOP", KEYS[1], len - rate)
end
return allow

--上面的版本有毛刺问题：第一分钟最后一秒和第二分中第一秒
--版本2
--local key = KEYS[1]
--
--local now = tonumber(ARGV[1])
--local window = tonumber(ARGV[2])
--local limit = tonumber(ARGV[3])
--
--local min_time = now - window
--
---- 1. 删除过期请求
--while true do
--    local item = redis.call('LINDEX', key, 0)
--
--    if not item then
--        break
--    end
--
--    if tonumber(item) > min_time then
--        break
--    end
--
--    redis.call('LPOP', key)
--end
--
---- 2. 判断当前窗口请求数
--local count = redis.call('LLEN', key)
--
--if count >= limit then
--    return 0
--end
--
---- 3. 加入当前请求
--redis.call('RPUSH', key, now)
--
---- 4. 设置过期时间
--redis.call('PEXPIRE', key, window)
--
--return 1