---
--- 滑动窗口算法
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by itianyu.
--- DateTime: 2026/9/6 14:23
---
local rate = tonumber(ARGV[1])
local window = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
redis.call("LPUSH", KEYS[1], now)
local len = tonumber(redis.call("LLEN", KEYS[1]))
redis.call("EXPIRE", KEYS[1], window / rate * 2)
local allow = true
if len > rate then
    --redis.log(redis.LOG_WARNING, "alllow...", window)
    if now - tonumber(redis.call("LINDEX", KEYS[1], len - 1)) <= window then
        allow = false
    end
    redis.call("RPOP", KEYS[1], len - rate)
end
return allow
