// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"algorithm/kubecc/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: KubeccHandler(serverCtx),
			},
		},
	)
}
