// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: adm.proto

package server

import (
	"context"

	"algorithm/rpc/adm/adm"
	"algorithm/rpc/adm/internal/logic"
	"algorithm/rpc/adm/internal/svc"
)

type AdmServer struct {
	svcCtx *svc.ServiceContext
	adm.UnimplementedAdmServer
}

func NewAdmServer(svcCtx *svc.ServiceContext) *AdmServer {
	return &AdmServer{
		svcCtx: svcCtx,
	}
}

func (s *AdmServer) Ping(ctx context.Context, in *adm.Request) (*adm.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
