// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: adm.proto

package adm_client

import (
	"context"

	"algorithm/rpc/adm/adm"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = adm.Request
	Response = adm.Response

	Adm interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAdm struct {
		cli zrpc.Client
	}
)

func NewAdm(cli zrpc.Client) Adm {
	return &defaultAdm{
		cli: cli,
	}
}

func (m *defaultAdm) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := adm.NewAdmClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
